### ISSUE TITLE
Add table for field translations (procurement method, status)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/bi.open-contracting.org#103]
Can put them all in the same table

**Comment by jpmckinney** [comment]
@Camilamila Any other fields to translate? Which status fields?

**Comment by Camilamila** [comment]
**tender/procurementMethod**



| Code | ES translation |
|--- | --- | 
|open | abierto|
selective | selectivo
limited | limitado 
direct | directo

**tender/status**
| Code | ES translation |
|--- | --- | 
| active | activo | 
pending | pendiente | 
cancelled | cancelado | 
unsuccessful | sin éxito

**bids/status**
| Code | ES translation |
|--- | --- | 
| Disqualified | descalificada | 
| Qualified | calificada | 
| InTreatment | pendiente |

**roles**
| Code | ES translation |
|--- | --- | 
| bidder | oferente | 
| supplier | proveedor |

**Comment by jpmckinney** [comment]
@vgeryarbc I've created a codelist table with the translations of field values.

method = /tender/procurementMethod
tenderStatus = /tender/status
bidStatus = /bids/details[]/status
partyRole = /parties[]/roles (array)

**Comment by vgeryarbc** [comment]
Added to solution.
