### ISSUE TITLE
Translation sheets

### ISSUE THREAD

**Issue by Camilamila** [open-contracting/bi.open-contracting.org#112]
@vgeryarbc Could you send the latest translation sheets, so that I can update the Spanish translation?

**Comment by vgeryarbc** [comment]
Attached.

[OCDS_DR_v53-Translations-FixedObjects.xlsx](https://github.com/open-contracting/bi.open-contracting.org/files/12762593/OCDS_DR_v53-Translations-FixedObjects.xlsx)
[OCDS_DR_v53-Translations-Master.xlsx](https://github.com/open-contracting/bi.open-contracting.org/files/12762594/OCDS_DR_v53-Translations-Master.xlsx)

**Comment by Camilamila** [comment]
Thanks Vadim, here are the updated translations to update the dashboard:

[OCDS_DR_v53-Translations-FixedObjects_UPDATED.xlsx](https://github.com/open-contracting/bi.open-contracting.org/files/12767856/OCDS_DR_v53-Translations-FixedObjects_UPDATED.xlsx)
[OCDS_DR_v53-Translations-Master_UPDATED.xlsx](https://github.com/open-contracting/bi.open-contracting.org/files/12767858/OCDS_DR_v53-Translations-Master_UPDATED.xlsx)

**Comment by vgeryarbc** [comment]
Updated. Please check.
