### ISSUE TITLE
Author help pages for individual reports or visualizations

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/bi.open-contracting.org#114]
(e.g. on use cases satisfied)

This can be done after initial testing with users, to prioritize content.

Not currently prioritized, but adding here as a reminder.

**Comment by Camilamila** [comment]
Similar to the methodology page for Ecuador, we want to add a methodology page to DR's BI.  

Here is the version in ES and EN:


Este tablero permite explorar diversos indicadores relacionados con medir potenciales riesgos o banderas rojas del mercado de compras públicas de República Dominicana.  

[Guía de Usuario](https://docs.google.com/document/d/1kPo9h7HqmmQPCbAVEW1naMf2TOtC3f8kFA6x4DNHYh0/edit?usp=sharing)


El tablero incluye una serie de banderas rojas calculadas utilizando [Cardinal](https://www.open-contracting.org/2024/06/12/cardinal-an-open-source-library-to-calculate-public-procurement-red-flags/), una herramienta desarrollada por Open Contracting Partnership de uso libre, para calcular automáticamente banderas rojas utilizando los datos de contratación pública en el Estándar de Datos para las Contrataciones Abiertas (OCDS).  

El listado de banderas calculadas se detalla en la siguiente tabla, con enlaces a la metodología de cálculo.   



Tipo de bandera | Nombre | Descripción | Unidad de cálculo | Fórmula de cálculo
-- | -- | -- | -- | --
Detección de riesgos  colusión | Diferencia similar entre precios de oferta | La diferencia porcentual entre los precios de oferta de dos oferentes es la misma en distintos procesos de contratación. | Proceso de contratación, oferente |  
Detección de riesgos  colusión | Precio cercano a la oferta ganadora | La diferencia porcentual entre la oferta ganadora y la segunda oferta válida más baja es un valor atípico bajo | Proceso de contratación, oferente |[R024](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/024.html)
Detección de riesgos  colusión | Número excesivo de ofertas no exitosas | La relación entre las ofertas ganadoras y las presentadas por un oferente es un valor atípico bajo | Oferente | [R025](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/025.html)
Detección de riesgos  colusión | Precios de oferta idénticos | Dos ofertas presentadas por diferentes oferentes tienen el mismo precio | Proceso de contratación, oferente | [R028](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/028.html)
Detección de riesgos  colusión | Oferta con precio muy bajo | La diferencia porcentual entre la oferta ganadora y la segunda oferta válida más baja es un valor atípico alto | Proceso de contratación, oferente | [R058](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/058.html)
Riesgos de adjudicación | Todas las ofertas son descalificadas excepto la ganadora | Las ofertas presentadas son descalificadas excepto la ganadora | Proceso de contratación, oferente | [R035](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/035.html)
Riesgos de adjudicación | Oferta más baja descalificada | La oferta más baja es descalificada cuando el criterio de adjudicación es solo precio | Proceso de contratación, oferente | [R036](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/036.html)
Riesgos de adjudicación | Alto número de ofertas descalificadas | La relación de ofertas descalificadas y las presentadas es un valor atípico alto para un comprador o un oferente | Comprador, oferente | [R038](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/038.html)
Riesgos de adjudicación | Oferta tardía gana | La oferta ganadora fue recibida después de la fecha límite de presentación | Proceso de contratación, oferente | [R030](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/030.html)
Riesgos de adjudicación | Proveedor multipropósito | La variedad de artículos suministrados por un oferente es un valor atípico alto | Oferente | [R048](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/048.html)



### Methodology

This dashboard allows you to explore various indicators related to measuring potential risks or red flags in the Dominican Republic’s public procurement market.  

[User Guide](https://docs.google.com/document/d/1kPo9h7HqmmQPCbAVEW1naMf2TOtC3f8kFA6x4DNHYh0/edit?usp=sharing)

The dashboard includes a series of red flags calculated using [Cardinal](https://www.open-contracting.org/2024/06/12/cardinal-an-open-source-library-to-calculate-public-procurement-red-flags/), a free-to-use tool developed by the Open Contracting Partnership to automatically calculate red flags using the public procurement data in the Open Contracting Data Standard (OCDS).  

The list of calculated flags is detailed in the table below, with links to the detailed methodology. 

Type of red flag | Name | Description | Unit of analysis | Formula
-- | -- | -- | -- | --
Collusion risk detection | The offers have an exact percentage difference | La percentage difference between the prices of the bids of two bidders is the same in different contracting processes  | Contracting process, bidder |  
Collusion risk detection| Price close to winning bid | The percentage difference between the winning bid and the second-lowest valid bid is a low outlier | Contracting process, bidder |[R024](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/024.html)
Collusion risk detection | Excessive unsuccessful bids | The ratio of winning bids to submitted bids for a top tenderer is a low outlier.| Bidder | [R025](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/025.html)
Collusion risk detection | Identical bid prices | Different tenderers submitted bids with the same price. | Contracting process, bidder | [R028](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/028.html)
Collusion risk detection | Heavily discounted bid | The percentage difference between the winning bid and the second-lowest valid bid is a high outlier | Contracting process, bidder | [R058](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/058.html)
Supplier risks | All except winning bid disqualified | Bids are disqualified if not submitted by the single tenderer of the winning bid | Contracting process, bidder | [R035](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/035.html)
Supplier risks | Lowest bid disqualified | The lowest submitted bid is disqualified, while the award criterion is price only | Contracting process, bidder | [R036](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/036.html)
Supplier risks | Excessive disqualified bids |The ratio of disqualified bids to submitted bids is a high outlier per buyer, procuring entity or tenderer | Buyer, bidder | [R038](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/038.html)
Supplier risks | Late bid won | The winning bid was received after the submission deadline | Bidder | [R030](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/030.html)
Supplier risks | Heterogeneous supplier | The variety of items supplied by a tenderer is a high outlier | Oferente | [R048](https://cardinal.readthedocs.io/en/latest/cli/indicators/R/048.html)

**Comment by vgeryarbc** [comment]
@Camilamila @jpmckinney please check !
![image](https://github.com/user-attachments/assets/ff711445-71c2-4e64-9150-85826e49f545)

I have added link buttons on Home and Individual Bidder&Supplier pages. Would you like to add link to the other places?
![image](https://github.com/user-attachments/assets/9315bb91-2b15-4283-b3f0-9fca9e0fd43b)

![image](https://github.com/user-attachments/assets/0933dfab-fc07-49cf-a3c2-27de4e7157d6)

**Comment by Camilamila** [comment]
Looks good!
