### ISSUE TITLE
Check chart on Individual Buyer dashboard

### ISSUE THREAD

**Issue by Camilamila** [open-contracting/bi.open-contracting.org#115]
The chart  **Count of red flags detected for buyer over time** is not showing information when selecting specific buyers.  

The chart should show: 

X-axis → Month and year
Y-axis → Count of red flags detected **for the contracting processes for the buyer**

![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/24500400/4dd68d3d-4cf1-4ce5-be4f-f40de92bc3ba)

**Comment by vgeryarbc** [comment]
May be "Count of buyer's contracting processes with red flags detected over time" (contract process can have more then one flag) ?

**Comment by Camilamila** [comment]
The current chart is correct.   

I noticed that if I try to access to the individual buyer dashboard, drilling through other dashboards (see image).  This chart is not showing.  But if I access the dashboard directly the chart appears.  


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/24500400/d0383580-9655-4ed9-b9ac-838a607d5b7a)

![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/24500400/5fcc5dcf-ad0e-4696-b908-fd4149ad9c87)

**Comment by vgeryarbc** [comment]
Fixed. Please check.
