### ISSUE TITLE
URGENT REVIEW: Check Individual contracting process dashboard

### ISSUE THREAD

**Issue by Camilamila** [open-contracting/bi.open-contracting.org#116]
The table: **List of bidders and bid amounts**   should show a list of ALL bidders and the bid amount, regardless if the same bidder submitted multiple bids.  Currently it seems you are aggregating by bidder and status.    

See example below for contracting process:  **ocds-6550wx-DGAP-CCC-PEEX-2021-0002**

![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/24500400/2aaa2354-9faa-4792-9da2-8ed076e8726d)

If you run this query, it yields more than 3 bids and none of the numbers equals that big number for the disqualified value (this seems to be a sum of all the disqualified bid amounts for that bidder):
`SELECT data->'bids'->'details' FROM dominican_republic_api WHERE data->>'ocid' = 'ocds-6550wx-DGAP-CCC-PEEX-2021-0002';`

**Comment by vgeryarbc** [comment]
OK, 
I have added 'Bid ID' to separate different bids from the same Bidder.
Please check.

**Comment by Camilamila** [comment]
Thanks Vadim!  It looks good now.
