### ISSUE TITLE
Add tile: Awards with competitive contracting processes 

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#12]
Tile details:

- [ ] Title: < Number > and < Percentage > Awards with competitive contracting processes

**Comment by vgeryarbc** [comment]
@jpmckinney @sabahfromlondon 
 Calculating of “number of awards of competitive contracting processes” and “number of singe bidder contracting processes” is based on  “Number of bidders” > 1 and = 1  or another approach assumed?

**Comment by jpmckinney** [comment]
I assume it means:

* number of single bidder contracting processes: procurementMethod != direct, number of **bids** = 1
* number of awards of competitive contracting processes: procurementMethod != direct, length(awards)

@Camilamila

**Comment by Camilamila** [comment]
Correct!  For competitive contracting processes use /tender/procurementMethod != 'direct'

**Comment by vgeryarbc** [comment]
OK, Thank you!

**Comment by Camilamila** [comment]
Remove decimals (not on %)

**Comment by jpmckinney** [comment]
Done

<img width="496" alt="Screenshot 2024-05-27 at 10 20 04 AM" src="https://github.com/open-contracting/bi.open-contracting.org/assets/26463/c9f27064-633f-4659-bfb0-5df406b01cd0">
