### ISSUE TITLE
U0## indicators

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/bi.open-contracting.org#120]
The [spreadsheet](https://docs.google.com/spreadsheets/d/11qQO6l4wgPQuH1aExST21XlyRG1uXOJiAldzz4r7NWI/edit#gid=808936397) has (machine-translated):

* U011 Percentage of tenders awarded through competitive procedures
* U014 Total value of assigned tenders through competitive procedures
* U015 Proportion of single offers tenders
* U016 Proportion of values awarded to tenders of unique offers against competitive tenders
* U017 Average number of bidders per bidding
* U019 Average number of bidders per type of article
* U020 Number of unique suppliers per type of article

I think these are all present on the Competition report. (If not, please correct me.)

I don't think they are appropriate for Cardinal, as they can fairly easily be calculated with SQL queries (which I think is what @vgeryarbc has already done for that report), and they are either one number for the entire dataset (UC011, 14, 15, 16, 17) or per item classification (UC019, 20).

@Camilamila Does that all sound right to you?

**Comment by Camilamila** [comment]
Yes agree!
