### ISSUE TITLE
R003: Minimum submission periods per procurement method

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/bi.open-contracting.org#121]
Here are the values of procurementMethodDetails. I need the minimum submission periods to configure and calculate the indicator.

```
       ? Catálogo electrónico
  148811 Subasta Inversa Electrónica
   51340 Menor Cuantía
   22971 Contratacion directa
   16689 Comunicación Social – Contratación Directa
   16569 Contratos entre Entidades Públicas o sus subsidiarias
   16554 Bienes y Servicios únicos
   12639 Cotización
    8889 Obra artística, científica o literaria
    7764 Repuestos o Accesorios
    3544 Licitación de Seguros
    3213 Lista corta
    2656 Licitación
    2490 Comunicación Social – Proceso de Selección
    1201 Contratación de Seguros
     720 Asesoría y Patrocinio Jurídico
     238 Transporte de correo interno o internacional
     184 Contratación Directa por Terminación Unilateral
     156 Concurso publico
      89 Contrataciones con empresas públicas internacionales
      50 Concurso Público por Lista Corta Desierta
      34 Asesoría y Patrocinio Jurídico – Cons. puntuales y específicas
      12 Lista Corta por Contratación Directa Desierta
       4 Concurso Público por Contratación Directa Desierta
```

I don't have the count for "Catálogo electrónico" yet, because Ecuador has values like "Catálogo electrónico - Compra directa en el convenio SICM-065-2022, ADQUISICION DE CATALOGO DE MEDICAMENTOS, SELECCIÓN DE PROVEEDORES PARA LA INCORPORACIÓN DE MEDICAMENTOS EN EL CATÁLOGO ELECTRÓNICO DEL PORTAL DE COMPRASPÚBLICAS", which I need to normalize.

**Comment by jpmckinney** [comment]
Alternatively, the procurementMethod values are:

```
1026222 selective
 751892 direct
 167860 open
   5715 limited
```

**Comment by jpmckinney** [comment]
@Camilamila Also, I'm not sure which submission periods are relevant for auctions. In addition to `tenderPeriod`, auctions have `/auctions[]/stages[]/rounds[]/period/endDate` and `/auctions[]/stages[]/rounds[]/period/startDate` (there is only ever one round, one stage, and one auction per contracting process).

**Comment by Camilamila** [comment]
Hi James!  Based on a call Guillermo had with Sercop, these are the minimum periods for open procedures.  So we should calculate this for open procedures only: 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-745ce401-7fff-9314-ab84-68a7f3903a71"><div dir="ltr" style="margin-left:0pt;" align="left">

method | Procurement method details | Minimum tender period
-- | -- | --
open | Concurso publico | Min 15 días max 30 días
open | Concurso Público por Contratación Directa Desierta | Min 15 días max 30 días
open | Concurso Público por Lista Corta Desierta | Min15 días max 30 días
open | Cotización | Min 7 días max 20 días
open | Licitación | Min 10 días max 40 días
open | Licitación de Seguros | Min 10 días max 40 días

</div></b>

**Comment by jpmckinney** [comment]
> @Camilamila Also, I'm not sure which submission periods are relevant for auctions. In addition to `tenderPeriod`, auctions have `/auctions[]/stages[]/rounds[]/period/endDate` and `/auctions[]/stages[]/rounds[]/period/startDate` (there is only ever one round, one stage, and one auction per contracting process).
> 
> Edit: There's also `/auctions[]/period`.

Do we care about these other periods, or do we only test the main `/tender/tenderPeriod`?

**Comment by Camilamila** [comment]
Hi James! We should only use the tender/tenderPeriod.  Only the open procedures mentioned above (not auctions) have a designated period.
