### ISSUE TITLE
NEW:  TOP filter

### ISSUE THREAD

**Issue by Camilamila** [open-contracting/bi.open-contracting.org#125]
Since the objetive of this dashboard is for the user to identify unit prices and prices discrepancies for a specific category, we should use the most granular category.  

For this dashboard for the top level filter, lets use ONLY the `awards[]/items[]/classification/id` and not the aggregated CPV leves (1 to 3) as it is now.

**Comment by vgeryarbc** [comment]
@Camilamila  please also note that we have two filters for items filtering on Price dashboard. The first is on top (to filter item categories 3-level hierarchy)  and the second on Table 'List of contracting processes that procured a particular item'. The second one filters ItemCalsifficationDescription which is defined by items[]/classification/id. So a user may select  item category group on top and then select exact ItemCalsifficationDescription  Table filter pane from shorter list. Filters apply to all dashboard visuals. 
Would you like to leave only one filter for ItemCalsifficationDescription and put it on top?

**Comment by vgeryarbc** [comment]
Put ItemCalsifficationDescription filter on top.
