### ISSUE TITLE
Adjust top filter

### ISSUE THREAD

**Issue by Camilamila** [open-contracting/bi.open-contracting.org#128]
Currently the search bar above includes all the items at the lowest level of classification, where we have unit values: awards[]/items[]/classification/id, however it's hard for the user to know to which higher level category this relates to.  To ease navigation can we, instead add the CPC 3 digits on top and then drill down to the item classifications?:

![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/24500400/e481f5ba-cb04-43b4-84b3-3aeb3584231f)

This allows the user to know to which higher level category the item belongs to. 

The charts below should be filtered according to this filter, since currently I see the tables, plots and tiles are not being filtered correctly.  For instance, in the example below, when I select and item category, its not filtering the number of procedures for that item category, and the table is not showing any procedures.  
![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/24500400/0ac7eb83-eb8d-46b5-a436-ae956df4ff71)
![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/24500400/746eb0ea-9d10-41f6-bad1-477c6b837d28)

**Comment by vgeryarbc** [comment]
Category 3-digit and (name) added.
Filtering should works. 


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/22bff1c4-8ef9-4853-bb17-04ec1c4598c3)

**Comment by vgeryarbc** [comment]
@Camilamila  could you check if that is OK?

**Comment by Camilamila** [comment]
Yes it works! thanks!
