### ISSUE TITLE
Add instruction on top

### ISSUE THREAD

**Issue by Camilamila** [open-contracting/bi.open-contracting.org#129]
Can we add a text on top of the tiles with instructions on how to navigate the dashboard? 

Please select the desired item category on top to review the historic unit prices and the details of past procedures.  You can select multiple item categories to compare.

ES:  Seleccione la categoría de artículo que desea analizar para ver sus precios históricos y los procesos de contratación relacionados.  Puede seleccionar varias categorías de artículos para comparar.

**Comment by vgeryarbc** [comment]
Instruction added.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/70b5d786-2eeb-4d76-8ae7-301be49cfb2a)
