### ISSUE TITLE
Add tile: Single bid tenders

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#13]
Tile details:

- [ ] Title: < Percentage > Single bid tenders

**Comment by Camilamila** [comment]
In the homepage, the chart "Proportion of contracting processes with single bidder only, where procurement method is open" shows that 21,7% of the competitive tenders had a single bid, however in this tile the proportion is 3.5%.  Could you clarify how are you calculating this and why the numbers differ?

**Comment by vgeryarbc** [comment]
On 'Home' page scope of contracting processes filtered to 'open' procurement method only. 
On 'Competition' page the scope is wider and includes 'selective' and 'limited'.

**Comment by vgeryarbc** [comment]
'Single bid tenders' on Competition page has been corrected to exclude "direct"  tenders (contract processes).
