### ISSUE TITLE
Check % in tiles when filtering by date

### ISSUE THREAD

**Issue by Camilamila** [open-contracting/bi.open-contracting.org#132]
I realized that when the date filter is applied in the [Risk to supplier dashboard](https://do.bi.open-contracting.org/) the % in the tiles is calculated based on the TOTAL number of bidders in the dataset and not on the total number of bidders for the period of the filter applied.  Can we correct this and make sure the filter is correctly applied in the other dashboards when calculating proportions?

<img width="621" alt="Screen Shot 2024-07-24 at 18 04 00" src="https://github.com/user-attachments/assets/cd272f40-943e-46c6-9538-56ddb37d9ff3">
<img width="623" alt="Screen Shot 2024-07-24 at 18 05 12" src="https://github.com/user-attachments/assets/b28c92a3-4f9f-49e6-a351-15cc6af298d0">

**Comment by vgeryarbc** [comment]
Corrected for total Bidders fall in the selected time period.
![image](https://github.com/user-attachments/assets/4d6b4bab-2047-4d51-a485-ad21569b46a2)
