### ISSUE TITLE
Add top filter: Procurement Method Details

### ISSUE THREAD

**Issue by Camilamila** [open-contracting/bi.open-contracting.org#133]
Can we add a top filter with the **Procurement Method Details** to all the dashboards (except individual contracting process)?

**Comment by vgeryarbc** [comment]
Will look like this, OK?
![image](https://github.com/user-attachments/assets/67d25af5-3684-4936-b129-f7d408693eab)

Would you like to delete that filter on pages where Procurement Method Details (named Competitive contracting process) is used inside.? For example on Competition page.
![image](https://github.com/user-attachments/assets/456d910f-80a8-4fed-8fd3-326f90b2e65d)

**Comment by Camilamila** [comment]
Yes the filter should be global, we can remove from the tables and keep just the one on top.

**Comment by vgeryarbc** [comment]
Done

![Image](https://github.com/user-attachments/assets/f03c1f29-36f1-46c3-a03d-e456b8856ae8)

**Comment by Camilamila** [comment]
Can we change the title of this filter:
EN:  Procurement method
ES: Tipo de procedimiento

**Comment by vgeryarbc** [comment]
@Camilamila we already have 'Procurement method" field and filter based on (on some pages). Filed contains 'direct', "selective' 'open e.t.c. 
May be another name?


![Image](https://github.com/user-attachments/assets/9f5be11e-48a7-4770-b9a2-fa3a8effad9c)

**Comment by Camilamila** [comment]
Hi Vadim, the filter should be using the variable Procurement Method Details, my suggestion is only to change the title for clarity, based on feedback from the partner, because it currently says competitive contracting process, but it should be:  

EN: Procurement method details
ES: Tipo de procedimiento

**Comment by vgeryarbc** [comment]
Title changed.


![Image](https://github.com/user-attachments/assets/d652aef3-f482-43f9-8a37-aefb667382d4)



![Image](https://github.com/user-attachments/assets/a8a94e09-c432-4e4b-a3ec-07da2e8c8342)

**Comment by jpmckinney** [comment]
@Camilamila Is this now closed?
