### ISSUE TITLE
Translation Document

### ISSUE THREAD

**Issue by Camilamila** [open-contracting/bi.open-contracting.org#134]
We need to review all text and translations in the dashboard, can you share the Excel file with the EN-ES translatations so that I can update, review and share back.  

Thanks!

**Comment by vgeryarbc** [comment]
@Camilamila please correct and send me back to update. Short 'how to..'  in header comments. 

[OCDS_ECUADOR_v17-Translations-FixedObjects.xlsx](https://github.com/user-attachments/files/16479008/OCDS_ECUADOR_v17-Translations-FixedObjects.xlsx)
[OCDS_ECUADOR_v17-Translations-Master.xlsx](https://github.com/user-attachments/files/16479009/OCDS_ECUADOR_v17-Translations-Master.xlsx)

**Comment by Camilamila** [comment]
Here are the updated translations.  
[OCDS_ECUADOR_v17-Translations-FixedObjects (1).xlsx](https://github.com/user-attachments/files/16510488/OCDS_ECUADOR_v17-Translations-FixedObjects.1.xlsx)
[OCDS_ECUADOR_v17-Translations-Master (1).xlsx](https://github.com/user-attachments/files/16510491/OCDS_ECUADOR_v17-Translations-Master.1.xlsx)

**Comment by vgeryarbc** [comment]
Updated. Please check.

**Comment by Camilamila** [comment]
Hi Vadim, here are some changes: 

I detected some typos, I made the changes (cells marked in red) in the sheet attached.
[OCDS_ECUADOR_v17-Translations-Master.xlsx](https://github.com/user-attachments/files/16580543/OCDS_ECUADOR_v17-Translations-Master.xlsx)


Also in the Individual Buyer dashboard, the top filter is not translated.  The translation should be:  **Seleccionar a la entidad contratante**
<img width="399" alt="Screen Shot 2024-08-12 at 12 47 39" src="https://github.com/user-attachments/assets/a752b1d6-dbc5-4e2b-b7d2-fe06794d5124">

**Comment by vgeryarbc** [comment]
Changes updated.
Individual Buyer filter updated.


![Image](https://github.com/user-attachments/assets/e5984e90-796a-40eb-a6ae-a445210c918c)
