### ISSUE TITLE
Add chart: Proportion of awards with competitive contracting processes over time

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#15]
Chart details:

- [ ] Type: Single Line Chart
- [ ] Title: Proportion of awards with competitive contracting processes over time
- [ ] Description: Identify which times of the year does competition suffer.
- [ ] X-axis → Month and year
- [ ] Y-axis → Proportion of awards

Additonal details: 
- Timestamp to use the date of the compiled release.  
- Zoom into shorter time periods.

**Comment by Camilamila** [comment]
Remove procedures without a tender date

**Comment by vgeryarbc** [comment]
Removed
