### ISSUE TITLE
Add chart: Proportion of total value awarded in  competitive contracting processes over time

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#16]
Chart details:

- [ ] Type: Single Line Chart
- [ ] Title: Proportion of total value awarded in  competitive contracting processes over time
- [ ] Description: Understand the amount of public spending that goes on competitive contracting processes.
- [ ] X-axis → Month and year
- [ ] Y-axis → Total value of awards  ($1,000)

Additional details:
- Add in a tooltip: “Proportion and total amount.”

**Comment by Camilamila** [comment]
Can we do the scale of the Y axis in millions instead of billions.
