### ISSUE TITLE
Add chart: Proportion of single bid tenders over time

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#17]
Chart details:

- [ ] Type: Single Line Chart
- [ ] Title: Proportion of single bid tenders over time
- [ ] Description: See if there are seasonal patterns in the  proportion of tenders that only have a single bidder. Note that you can have a competitive process, but still only have a single bidder.
- [ ] X-axis → Month and year
- [ ] Y-axis → Proportion of awards

Additional details:
- **Calculate this only for competitive contracting proceses.**

**Comment by Camilamila** [comment]
Remove procedures without a tender date

**Comment by jpmckinney** [comment]
Reopening since you have a new instruction.

**Comment by jpmckinney** [comment]
Your comment is identical in #15 so just checking whether your comment here is by accident.

**Comment by Camilamila** [comment]
The comment is correct, both charts are similar, and we should remove procedures for this chart without a date.

**Comment by vgeryarbc** [comment]
Removed
