### ISSUE TITLE
Add chart: Mean number of bidders for a contracting process per item category

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#19]
Chart details:

- [ ] Type: Horizontal bar chart
- [ ] Title: Mean number of bidders for a contracting process per item category
- [ ] Description: See if there are item categories that are more competitive than others.
- [ ] X-axis → Mean number of bidders
- [ ] Y-axis → Number of unique bidders

Additonal details:
- Only the top 10 bars to be displayed. ‘See all’ button to view in a table.
- Add in tooltip: number of contracting processes for the specific item category.
- **Need to check if there are outliers, e.g  item categories with very few procedures and a high average, to evaluate if we should filter only for top item categories.**

**Comment by vgeryarbc** [comment]
X-axis → Item category 
 Y-axis → Number of unique bidders

**Comment by Camilamila** [comment]
Add in tooltip number of contracting processes

**Comment by vgeryarbc** [comment]
"Number of tenders" tooltip added
