### ISSUE TITLE
Add chart: Contracting processes with red flags detected over time

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#2]
Chart details:
- [ ] Type: Single line chart
- [ ] Title: Contracting processes with red flags detected over time
- [ ] Description: Visualise the overall trend to see if the number of contracting processes with red flags is getting better or worse over time or if there are specific times of the year when red flags are more likely to occur.
- [ ] X-axis → Month and year
- [ ] Y-axis → Proportion of contracting processes with red flags

Additional details:
- Timestamp to use the date of the compiled release
- Zoom into shorter time periods

**Comment by Camilamila** [comment]
The X axis should be the proportion.  The number of procedures flagged can be added to the tooltip

**Comment by vgeryarbc** [comment]
Replaced with proportion and added tooltip
