### ISSUE TITLE
Add chart: Number of unique suppliers for a contracting process per item category

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#20]
Chart details:

- [ ] Type: Horizontal bar chart
- [ ] Title: Number of unique suppliers for a contracting process per item category
- [ ] Description: See which item categories are more likely to end up with multiple suppliers contributing to fulfilling a contract.
- [ ] X-axis → Number of unique suppliers
- [ ] Y-axis → Item category

Additional details:
- Only the top 10 bars to be displayed. ‘See all’ button to view in a table.
- This considers all tenders not only competitive ones.
- Add in a tooltip: Number of contracting processes for the specific item category

**Comment by Camilamila** [comment]
Title should be: Number of unique suppliers per item category

**Comment by Camilamila** [comment]
Add in  tooltip: Number of contracting processes for the specific item category

**Comment by vgeryarbc** [comment]
"Number of tenders" tooltip added

**Comment by Camilamila** [comment]
Re-opening this since the title needs to be adjusted:  

Title should be: Number of unique suppliers per item category

**Comment by jpmckinney** [comment]
FYI, Need to click "Reopen" to reopen :)

**Comment by vgeryarbc** [comment]
Corrected to "Number of unique suppliers per item category"


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/f3b68ceb-e5e4-4093-9eeb-5e6d25b63c25)
