### ISSUE TITLE
Add table: List of contracting processes and details of competitiveness

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#22]
Table details:

- [ ] Title: List of contracting processes and details of competitiveness.
- [ ] Description: This table lists contracting processes and details of the competitiveness of those contracting processes.

Filters:
- [ ] Ocid
- [ ] Buyer name
- [ ] Item category
- [ ] Date
- [ ] Competitive contracting process

Columns:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-b09f622d-7fff-d77b-cac7-4de9b2847dce"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
OCID | The OCDS field ocid. The globally unique identifier for this Open Contracting Process. | Users can click on an OCID to view the specific contracting process, in the Individual Contracting Process dashboard.
Buyer name | The name of the buyer using the OCDS field buyerName. Alternatively use tender/procuringEntity. | Users can click on the buyer name to go to the Individual Buyers Dashboard. Filter for a specific buyer.
Tender title | The title of the tender per the OCDS field tender/title. |  
Item category | The classification of the item using the OCDS field tender/items/classification/ description and the high level codes. Ecuador uses an internal classification scheme CPC. | Users can filter for a specific category.
Date | The timestamp for the contracting process using the OCDS field tender/period/startDate. | Users can filter the contracting processes by selecting a date
Tender value | The value of the contract and the currency. OCDS fields tender/value/amount and tender/value/currency. | Users can sort by value amount e.g. highest to lowest.
Competitive contracting process | The different types of open contracting processes using the OCDS field tender/procurementMethodDetails |  
Number of unique bidders | The number of parties who submit a bid as per the OCDS field tenderNumberOfTenderers. | Number of unique bidders
Supplier name | The name of the awarded supplier. The OCDS field is parties/name, where roles= ‘supplier’. The field award/supplier/name may also be used. | Can be more than one supplier. If so have all suppliers on one row, semi colon separated

</div></b>
</body>
</html>

**Comment by vgeryarbc** [comment]
Added 'Contract value' column after 'Tender value'.

**Comment by Camilamila** [comment]
Is this table only considering open procedures?

**Comment by vgeryarbc** [comment]
> Is this table only considering open procedures?

There are no special filters applied, Contract processes with all 'ProcurementMethod's (direct, limited, open, selective)  are shown.

**Comment by Camilamila** [comment]
This should only include open procedures.

**Comment by jpmckinney** [comment]
Thank you for clarifying :)

Your earlier question "Is this table only considering open procedures?" didn't make clear the desired behavior.

**Comment by vgeryarbc** [comment]
@jpmckinney @Camilamila "open" ProcurementMethod filter applied.
"Selective" is not, Is it correct ?  
![image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/b6129a05-3482-4bd1-9787-9310b2f5215c)

**Comment by Camilamila** [comment]
In this case, please include **selective and open**, since in both methods competition happens.

**Comment by vgeryarbc** [comment]
OK. 'selective' and 'open' filtered.

**Comment by Camilamila** [comment]
Hi Vadim,

We noticed that in this table, if there are multiple bidders the table duplicates the process showing one row per bidder.  There should be just one row per procedure, and the column: `Supplier name` should show just the name of the awarded supplier, we dont need the list of all bidders.

**Comment by Camilamila** [comment]
Change ocid filter to `tender/id`.  If possible, can we remove the characters after the last '-'.  For example:

If the `tender/id` is:  `001-LICS-HGFO-2023-54538`,  the value shoulde be `001-LICS-HGFO-2023`

**Comment by vgeryarbc** [comment]
Changed


![Image](https://github.com/user-attachments/assets/10f06fbf-4330-4052-a499-bfa2152066fc)
