### ISSUE TITLE
Add tile: Contracting processes with competition red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#23]
Tile details:

- [ ] < Number > and < Percentage > Contracting processes with competition red flags

**Comment by vgeryarbc** [comment]
At present no 'competition' red flags found in `ecuador_sercop_bulk_result`

**Comment by vgeryarbc** [comment]
At present, data for that flag (R018) are randomly emulated because we do not have that data in DB. When real flag data comes to db it will be OK.
The same is for R017 and HHI index.

**Comment by Camilamila** [comment]
Can we remove the decimals from integers (not %)

**Comment by jpmckinney** [comment]
> Do we have new data for R018, R017 ?

Not yet

**Comment by jpmckinney** [comment]
Decimals removed

<img width="492" alt="Screenshot 2024-05-27 at 10 00 22 AM" src="https://github.com/open-contracting/bi.open-contracting.org/assets/26463/b0eb15bc-31a6-4484-99e2-d9a40d066604">
