### ISSUE TITLE
Add chart: Buyers with highest proportion of competition red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#29]
Chart details:

- [ ] Type: Horizontal bar chart
- [ ] Title: Buyers with highest proportion of contracting processes with competition red flags
- [ ] Description: See which buyers have a higher proportion of competition red flags
- [ ] X-axis → %
- [ ] Y-axis → Buyer name

Additional details:
- Exclude buyers with very few procedures.  Check in the data what is the reasonable threshold.  Eg. > 100 procedures.
- Only the top 10 bars with the highest proportion are to be displayed.

**Comment by sabahfromlondon** [comment]
@Camilamila we might need to shorten the y-axis label. Suggest we use the % sign

**Comment by Camilamila** [comment]
Agree

**Comment by vgeryarbc** [comment]
'Buyers with highest proportion of competition red flags' or 'Buyers with highest proportion of **contracting processes** with competition red flags' ?

**Comment by Camilamila** [comment]
It would be:  'Buyers with highest proportion of contracting processes with competition red flags'

**Comment by Camilamila** [comment]
Can we adjust the tooltip?  The title of the second value shown should be: % of flagged procedures 
<img width="423" alt="Screen Shot 2024-07-04 at 15 58 26" src="https://github.com/open-contracting/bi.open-contracting.org/assets/24500400/1b01ce2d-a22a-4d0d-abf0-e6671cbc6647">

**Comment by vgeryarbc** [comment]
Fixed.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/a0aecb5a-719e-4f08-9085-004c269b501b)



![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/1a9550fe-2af6-45ff-b20a-6cc540109a1e)
