### ISSUE TITLE
Add tile: Total number of contracting processes

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#3]
Tile details:

- [ ] Title: < Number > and < Percentage > Contracting processes with red flags detected over time

**Comment by vgeryarbc** [comment]
I think it should be 
Title: < Number > Number of Contracting processes 

(we do have another tile #7  for contracting processes with RF)

**Comment by jpmckinney** [comment]
Agree - looks like a typo.
