### ISSUE TITLE
Add chart: Collusion red flags frequency

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#33]
Chart details:

- [ ] Type: Horizontal bar chart
- [ ] Title: Collusion red flags frequency
- [ ] Description: Identify which collusion red flags are most prevalent.
- [ ] X-axis → Number of contracting processes flagged
- [ ] Y-axis → Red flag name

**Comment by sabahfromlondon** [comment]
@Camilamila the x-axis label is likely to be too long

**Comment by Camilamila** [comment]
Updated!
