### ISSUE TITLE
Add chart: Buyers with the highest proportion of contracting processes with 1+ collusion red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#34]
Chart details:

- [ ] Type: Horizontal bar chart
- [ ] Title: Buyers with the highest proportion of contracting processes with 1+ collusion red flags
- [ ] Description: Identify which buyers have a higher risk collusion occurring.
- [ ] X-axis → Proportion of contracting processes with collusion red flags (0-100%)
- [ ] Y-axis → Buyer name

Additional details:
- Only the top 10 bars to be displayed. ‘See all’ button to view in a table.
- Add tooltip with number of procedures.  
- Exclude buyers with very few procedures. Check in the data what is the reasonable threshold.  Eg. > 100 procedures.

**Comment by Camilamila** [comment]
In this chart, the buyer with the highest proportion is not shown in the TOP 10, but it appears as the top buyer when selecting all buyers.  Why is this happening? 
<img width="637" alt="Screen Shot 2024-07-08 at 11 20 31" src="https://github.com/open-contracting/bi.open-contracting.org/assets/24500400/aa9b36ac-082c-4583-a774-7946b80d335f">
<img width="600" alt="Screen Shot 2024-07-08 at 11 20 11" src="https://github.com/open-contracting/bi.open-contracting.org/assets/24500400/60ff2a90-92bf-41d1-a31f-7ca06096d42a">

**Comment by vgeryarbc** [comment]
Fixed Top10 tab. 


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/6101c929-a3b7-4e0d-9b98-29dc43547abe)
