### ISSUE TITLE
Add table: List of contracting processes with collusion red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#36]
Table details:

- [ ] Title: List of contracting processes with collusion red flags
- [ ] Description: This table lists all contracting processes with collusion red flags. Identify the riskiest contracting processes by sorting the list.

Filters:
- [ ] Ocid
- [ ] Buyer name
- [ ] Item category
- [ ] Date range
- [ ] Status

Columns:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-4ec659b8-7fff-5d49-9e5b-1557e0702259"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
OCID | The OCDS field ocid. The globally unique identifier for this Open Contracting Process. | Users can click on an OCID to view the specific contracting process, in the Individual Contracting Process dashboard.
Buyer | The name of the buyer using the OCDS field buyerName. Alternatively use tender/procuringEntity. | Users can click on the buyer name to go to the Individual Buyers Dashboard. Users can filter for a specific buyer.
Tender title | The title of the tender per the OCDS field tender/title. |  
Item category | The classification of the item using the OCDS field tender/items/classification/ description and the high level  codes.  Ecuador uses an internal classification scheme CPC. | Users can filter for a specific category
Date | The timestamp for the red flag using the OCDS field tender/startDate. | Users can filter the contracting processes by selecting a date range.
Status | The current status of the tender, from the closed tenderStatus codelist, using the OCDS field tender/status. | Users can filter by status using a dropdown with the different options.
Supplier name | Name of the awarded supplier. | If multiple suppliers are awarded, separate by ;
Count of red flags | This is the total of all of the collusion red flags detected in the contracting process. | Users to see visually via a colour scale which contracting processes are more problematic. Scale is for 1-9 red flags.Users can sort by value amount e.g. highest to lowest.Include note to state that buyers that are involved in more contracting processes are likely to have more red flags.
Red flag name | This indicates if the red flag is present. A column for each flag should be added (see table below). | Users to see visually via colour that there is a red flag.The column headings will have names for each flag rather than F1, F2…

</div></b>
</body>
</html>

**Comment by Camilamila** [comment]
the ocid filter is missing

**Comment by vgeryarbc** [comment]
OCID filter added

**Comment by jpmckinney** [comment]
>> the ocid filter is missing

> OCID filter added

Confirmed. Closing.
<img width="450" alt="Screenshot 2024-05-16 at 9 12 50 PM" src="https://github.com/open-contracting/bi.open-contracting.org/assets/26463/a4a42796-0a60-4df3-84d0-d2df34e9f02b">

**Comment by Camilamila** [comment]
Instead of `tender/title` can we use the field `tender/description`?

**Comment by vgeryarbc** [comment]
Title replaced with Description.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/ac301420-48f5-4321-9b79-0a28dd1b213a)

**Comment by Camilamila** [comment]
Change ocid filter to `tender/id`.  If possible, can we remove the characters after the last '-'.  For example:

If the `tender/id` is:  `001-LICS-HGFO-2023-54538`,  the value shoulde be `001-LICS-HGFO-2023`

**Comment by vgeryarbc** [comment]
Changed


![Image](https://github.com/user-attachments/assets/3a2c0560-aca6-4291-a6aa-8f355e05ca29)
