### ISSUE TITLE
Add tile: Contracting processes with tender value higher or lower than average

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#37]
Tile details:
- [ ] < Number > and < Percentage > Contracting processes with tender value higher or lower than average

**Comment by vgeryarbc** [comment]
How do you define upper and lower bounds from average to count contracting processes fallen within?

**Comment by jpmckinney** [comment]
@sabahfromlondon I don't see what visual is related to this requirement in the [design](https://docs.google.com/spreadsheets/d/14cdWoJo30n3Gc8mj0sr2knWEkUntun20N6t64O-Qd5k/edit#gid=1519897106).

In the requirements document, there is only the text as in this issue description.

However, by definition, "Contracting processes with tender value higher or lower than average" will always yield 50% higher and 50% lower (and equal number above and below).

@vgeryarbc For now, ignore this issue.

**Comment by vgeryarbc** [comment]
Removed.
