### ISSUE TITLE
Add tile: Contracting processes with items with unreasonable prices

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#38]
tile details:
- [ ] < Percentage > Contracting processes with items with unreasonable prices

**Comment by vgeryarbc** [comment]
Does "unreasonable price" attribute  come from flag data or have to be calculated in other way?

**Comment by jpmckinney** [comment]
@Camilamila We don't have any [flags](https://docs.google.com/spreadsheets/d/11qQO6l4wgPQuH1aExST21XlyRG1uXOJiAldzz4r7NWI/edit#gid=808936397) that match "unreasonable price".

I'm not sure where this requirement in the document comes from (it's not in the design).

We can either:

1. Close this issue and ignore this requirement
2. Come up with some new tile that relates to a red flag we actually calculate

**Comment by Camilamila** [comment]
This would be related to R017.

**Comment by vgeryarbc** [comment]
So, I am currently  using R017 to calculate 'unreasonable prices' contracting processes

**Comment by Camilamila** [comment]
Can we add the number of contracting processes and %

**Comment by vgeryarbc** [comment]
Added % of contracts with unreasonable price and total number of contracting processes

**Comment by jpmckinney** [comment]
R017 is not implemented. But, as far as Power BI is concerned, this issue seems complete.
