### ISSUE TITLE
Add chart: Item categories with a higher proportion of price related flagged contracting processes

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#39]
Chart details:

- [ ] Type: Horizontal bar chart
- [ ] Title: Item categories with a higher proportion of price related flagged contracting processes
- [ ] Description: Identify which item categories have a higher proportion of contracting processes with price related red flags.
- [ ] X-axis → Proportion of contracting processes in item category with price red flags
- [ ] Y-axis → Item category

Additional details:
- Only the top 10 bars to be displayed. ‘See all’ button to view in a table.
- Red flags are tender value higher or lower than average, items with unreasonable prices.
- Add tooltip for the number of contracting processes for the item category.

**Comment by Camilamila** [comment]
This aggregates by level 2 of CPV codes

**Comment by vgeryarbc** [comment]
By level 3 if count from 1 to 3. Level 3 is the lowest level of item categories.

**Comment by jpmckinney** [comment]
> By level 3 if count from 1 to 3. Level 3 is the lowest level of item categories.

@Camilamila Please review.

**Comment by Camilamila** [comment]
Lets remove this chart.

**Comment by jpmckinney** [comment]
<img width="681" alt="Screenshot 2024-06-13 at 6 37 04 PM" src="https://github.com/open-contracting/bi.open-contracting.org/assets/26463/01dcd714-eead-41d2-95e9-e678f1bcf5d5">

For future reference.

**Comment by vgeryarbc** [comment]
Chart removed.
