### ISSUE TITLE
Add chart: Price distribution per item category

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#41]
Chart details:

- [ ] Type: Box plot
- [ ] Title: Price distribution per item category
- [ ] Description: Compare the unit price distribution between different item categories.
- [ ] X-axis → Item category
- [ ] Y-axis → Unit price

Additional details:
- One box plot for each price category. Users can select the item category using the dropdown.
- Users can select up to 5 item categories to compare.
- Include only item categories with a reasonable number of procedures.  We need to check the data to select the threshold.

**Comment by vgeryarbc** [comment]
Same 'unit price for item category ' question as for #40

**Comment by vgeryarbc** [comment]
Added little right zone to indicate  selected 'Item classification data points' if any.

**Comment by vgeryarbc** [comment]
@Camilamila  By same as #40 do you mean scaling?  
Green points show classificationID related data.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/929644c8-7bbe-4af6-b51b-3d30bd1569ea)

**Comment by Camilamila** [comment]
Lets remove this chart.

**Comment by jpmckinney** [comment]
Would the chart work if we used log scale?

**Comment by Camilamila** [comment]
I think that would make it more confusing for the user. The problem with this chart is that is mixing different items from the same high level CPC code, while the original idea was to compare the distribution of the same exact units (lower level).  However I think the chart above on the prices over time, gives the user an idea of the evolution of the price.  

The main use case of this view is that SERCOP doesnt have a "price bank" so they want to be able to know for X item at what prices it has been procured, so I think that with the chart over time, and the list of procedures they can get an idea.

**Comment by jpmckinney** [comment]
I see, thanks. Yes let’s remove.

In the issue description, I think Sabah’s idea was to let users pick the categories. However, Power BI (as I understand) can only apply a single set of filters to all visualizations, and doesn’t have functionality to have filters specific to one chart. So this chart has to show a lot of categories to start with, and that yields a result we don’t want.

**Comment by Camilamila** [comment]
@vgeryarbc not sure if you saw this issue.

**Comment by vgeryarbc** [comment]
Chart removed.
