### ISSUE TITLE
Add table: List of contracting processes that procured a particular item

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#42]
Table details:

- [ ] Title: List of contracting processes that procured a particular item
- [ ] Description: This table lists all of the contracting processes that have procured a particular item. Each contracting process can have multiple items and different quantities of an item.

Filters:
- [ ] Ocid
- [ ] Buyer name
- [ ] Procurement method 
- [ ] Procurement method details
- [ ] Date range
- [ ] Status
- [ ] Item category

Columns:

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-509ddf24-7fff-44f5-4b1b-7971d593e2fd"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
OCID | The OCDS field ocid. The globally unique identifier for this Open Contracting Process. | Users can click on an OCID to view the specific contracting process, in the Individual Contracting Process dashboard.
Buyer | The name of the buyer using the OCDS field buyerName. Alternatively use tender/procuringEntity. | Users can click on the buyer name to go to the Individual Buyers Dashboard. Users can filter for a specific buyer
Procurement method | The method used to procure the goods/services. The OCDS field is tender/procurementMethod | Users can filter by procurement method
Procurement method details | The details of the method used to procure the goods/services. The OCDS field is tender/procurementMethodDetails | Users can filter by procurement method details
Date | The timestamp for the red flag using the OCDS field tender/startDate. | Users can filter the contracting processes by selecting a date range.
Status | The current status of the tender, from the closed tenderStatus codelist, using the OCDS field tender/status. | Users can filter by status
Tender title | The title of the tender per the OCDS field tender/title. |  
Item category | The classification of the item using the OCDS field tender/items/classification/ description and the high level  codes.  Ecuador uses an internal classification scheme CPC. | Users can filter for a specific category.If a tender has multiple items separate into different rows.
Quantity | The number of units to be provided. The OCDS field is tender/items/quantity. |  
Unit | The description of the unit in which the supplies, services or works are provided (e.g. hours, kilograms). The OCDS field is tender/items/unit. |  
Item unit value | The value of the item and the currency. OCDS fields tender/items/unit/value/amount and tender/items/unit/value/currency. | Users can sort by value amount e.g. highest to lowest.
Number of unique bidders | The number of parties who submit a bid as per the OCDS field tenderNumberOfTenderers. |  
Supplier name | The name of the entity supplying the goods/services. The OCDS field supplier/name. | Users can click on the supplier name to go to the Individual Suppliers Dashboard. Users can filter for a specific supplier
Region | Region of the supplier. The OCDS field is parties/address/region. | Region is for the supplier
Locality | Locality of the supplier. The OCDS field is parties/address/locality. | Locality is for the supplier

</div></b>
</body>
</html>

**Comment by Camilamila** [comment]
Include Procurement Method Details in the table.

**Comment by vgeryarbc** [comment]
Included.

**Comment by Camilamila** [comment]
Which filter is being applied to this table?  It should include ALL the procedures selected in the top filter

**Comment by Camilamila** [comment]
Instead of `tender/title` can we use the field `tender/description`?

**Comment by vgeryarbc** [comment]
Changed to tender/description.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/eaf0ef19-1824-47b3-8699-b176dd07fa14)

**Comment by Camilamila** [comment]
Change ocid filter to `tender/id`.  If possible, can we remove the characters after the last '-'.  For example:

If the `tender/id` is:  `001-LICS-HGFO-2023-54538`,  the value shoulde be `001-LICS-HGFO-2023`

**Comment by vgeryarbc** [comment]
Changed


![Image](https://github.com/user-attachments/assets/716469cb-d04c-4026-8605-ceeb73109878)
