### ISSUE TITLE
Add table: List of item categories and details of their price distribution

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#43]
Table details:

- [ ] Title: List of item categories and details of their price distribution
- [ ] Description: This table lists for all item categories, details of their unit price distribution and the number of procedures.  You can use this table to identify average unit prices and market concentration.

Filters:

- [ ] Item category

Columns:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-5f054977-7fff-0a40-71ab-4aa52d73c1d7"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
Item category | The classification of the item using the OCDS field tender/items/classification/ description and the high level codes. | Users can filter for a specific category
Number of contracting processes | This is the count of the contracting processes for the item category. |  
Market concentration | This is a calculation that uses the Herfindahl–Hirschman Index (HHI). Formula → HHI = s21 + s22 + s23 + s24 + ….s2nwhere S2n = the market share percentage of firm n expressed as a whole number.HHI can range from close to 0 (near perfect competition) to 10,000 (a monopoly). |  
Average unit price | This is a calculated field. |  
Median unit price | This is a calculated field. |  
Standard deviation of the unit price | This is a calculated field. |  

</div></b>
</body>
</html>

**Comment by jpmckinney** [comment]
@Camilamila @vgeryarbc  Related to #40, we discussed on the call changing the dropdown to use the `/awards[]/items[]/classification/description` in the dropdown (instead of the label from the `cpc` table), and to use the full `/awards[]/items[]/classification/id` value – because when comparing unit prices, we want to use precise items.
