### ISSUE TITLE
Add tile: Bidders with ‘competition’ red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#48]
Tile details:
- [ ] < Number > and < Percentage > Bidders with ‘competition’ red flags

**Comment by Camilamila** [comment]
Also can you remove the tile "Bidders with Risk to supplier red flags" (There is no issue for this one)

**Comment by vgeryarbc** [comment]
Both 'Bidders with competition..' and 'with risk to the supplier ...' tiles removed


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/457c3670-5a51-415f-9b35-9196d2a34f53)
