### ISSUE TITLE
Add tile: Bidders with ‘collusion detection’ red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#49]
Tile details:
- [ ] < Number > and < Percentage > Bidders with ‘collusion detection’ red flags

**Comment by Camilamila** [comment]
Remove tile

**Comment by vgeryarbc** [comment]
Removed.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/d0b6551a-d8c4-49a3-b410-6e985f0e9e90)
