### ISSUE TITLE
Add table: Flagged bidders with information from the contracting process

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#54]
Table details:

- [ ] Title: Flagged bidders with information from the contracting process
- [ ] Description: A full list of flagged suppliers and bidders and the contracting process associated. Filter by ocid, Buyer Name, Supplier, Item Category or by the procurement method.

Filters:
- [ ] Ocid
- [ ] Buyer name
- [ ] Date range
- [ ] Procurement method
- [ ] Supplier/bidder

Columns:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-704c0a53-7fff-137c-d224-b96aea0d5133"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
OCID | The OCDS field ocid. The globally unique identifier for this Open Contracting Process | Each field should link to the specific contracting process, viewable in the Individual Contracting Process dashboard.
Buyer | The name of the entity procuring the goods/services. The OCDS field buyerName. Alternatively use tender/procuringEntity. | Users can click on the buyer name to go to the Individual Buyers Dashboard. Users can filter for a specific buyer
Date | The timestamp for the red flag using the OCDS field tender/startDate. | Users can filter the contracting processes by selecting a date range.
Tender title | The title of the contract as per the OCDS field tender/title. | Each field should link to the specific contracting process, viewable in the Individual Contracting Process dashboard.
Procurement method | Method used to procure goods/services from the closed method codelist. Methods are: ‘open’, ‘selective’, ‘limited’, ‘direct’. | Users can filter by method using a dropdown with the four options.
Tender value | The value of the contract and the currency. OCDS fields tender/valueAmount and tender/valueCurrency. | Users can sort by value amount e.g. highest to lowest.
Supplier/Bidder name | The name of the bidder. The OCDS field is parties/name. The field award/supplier/name may also be used. | Users can filter for a specific name using search and select.
Role | The role of the party that was either a supplier or bidder from the party role codelist. The OCDS field is parties/roles. | Users can filter by role using a dropdown with the four options.
Number of bidder red flags | The count of red flags for the bidder in that contracting process | Users can sort by value amount e.g. highest to lowest.
Bidder red flag name | This indicates if the red flag is present. A column for each flag should be added | The column headings to have names for each flag

</div></b>
</body>
</html>

**Comment by Camilamila** [comment]
Instead of `tender/title` can we use the field `tender/description`?

**Comment by vgeryarbc** [comment]
Changed to tender/description.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/cefc98c5-8d4e-4384-8a6f-97862349fcac)

**Comment by Camilamila** [comment]
The tender value in the table seems to be empty for all procedures, can we use the contract or award value column instead?

**Comment by vgeryarbc** [comment]
Tender values replaced with contract values. Is it OK ?  (I see that Tender values exist for ~ 1/3 of contracting processes  in 2023-2024.)


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/d1bf0b00-58ae-4435-bea1-1f1ec5699833)

**Comment by Camilamila** [comment]
Change ocid filter to `tender/id`.  If possible, can we remove the characters after the last '-'.  For example:

If the `tender/id` is:  `001-LICS-HGFO-2023-54538`,  the value shoulde be `001-LICS-HGFO-2023`

**Comment by vgeryarbc** [comment]
Changed


![Image](https://github.com/user-attachments/assets/691f2332-02be-4433-b8bb-b6f9c0157323)
