### ISSUE TITLE
Add table: List of bidders that have the same address

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#55]
Table details:

- [ ] Title: List of bidders that have the same address
- [ ] Description: A list of when two different bidders have the same address. The table highlights where potential co-bidding has occurred and how often two companies are behaving in this way.

Filters:

- [ ] Bidder
- [ ] OCID

Columns:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-5c9cbc19-7fff-a4e2-39fc-be900e2d20d8"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
Bidder 1 name | The name of the company with the address that has bid / tendered. | Each field should link to the bidder, in the Individual Supplier dashboard.
Bidder 2 name | The name of the company with the address that has bid / tendered. | Each field should link to the specific bidder, viewable in the Individual Supplier dashboard.
Address | The address of both the bidders. The OCDS field is parties/address. | Only bidders that have this specific red flag to be included in this table.
Count of contracting processes where co-bidding occurred | The number of contracting processes where the same two companies have bid. |  
List of contracting process OCIDs | A list of OCIDs where the same two companies have bid / tendered. The OCDS field is ocid. | Each field should link to the specific contracting process, viewable in the Individual Contracting Process dashboard.

</div></b>
</body>
</html>

**Comment by jpmckinney** [comment]
Table differs only slightly from description. Closing.

<img width="1379" alt="Screenshot 2024-05-16 at 9 16 41 PM" src="https://github.com/open-contracting/bi.open-contracting.org/assets/26463/88959810-3cbb-4b9b-9573-61391500fbe2">
