### ISSUE TITLE
Add table: List of bidders that have the same personnel

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#56]
Table details:

- [ ] Title: List of bidders that have the same personnel
- [ ] Description: A list of when two different bidders have the same personnel. The table highlights where potential co-bidding has occurred and how often two companies are behaving in this way.

Filters:

- [ ] Bidder
- [ ] Ocid

Columns:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-635afc6a-7fff-e69d-b3f1-640cc24b3ba9"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
Bidder 1 name | The name of the company with the address that has bid / tendered. | Each field should link to the supplier in the Individual Suppliers & Bidders dashboard.
Bidder 2 name | The name of the company with the address that has bid / tendered. | Each field should link to the supplier in the Individual Supplier & Bidders dashboard.
Personnel | The name of personnel for both the bidders. The OCDS field is parties/contactPoint/name |  
Count of contracting processes where co-bidding occurred | Count of contracting processes where the same two companies have bid / tendered. |  
List of contracting processes OCIDs | OCIDs where the same two companies have bid / tendered. The OCDS field is ocid. | This is an array.

</div></b>
</body>
</html>

**Comment by Camilamila** [comment]
This table is currently empty.  Are there no coincidences in the data? If there are not, we can remove this table

**Comment by vgeryarbc** [comment]
Hi @Camilamila !
Same personnel analysis is based on contactPoint data field. At present there are no ocids where two or more bidders with the same contactPoint participated and table is empty

**Comment by jpmckinney** [comment]
Yes, we discovered the same in https://github.com/open-contracting/cardinal-rs/issues/94 and focus on addresses instead (for which there is a table https://github.com/open-contracting/bi.open-contracting.org/issues/55)

@Camilamila Shall we remove this table?

**Comment by Camilamila** [comment]
Yes

**Comment by vgeryarbc** [comment]
Removed.
