### ISSUE TITLE
Add table: List of bidder pairs with collusion red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#57]
Table details:

- [ ] Title: List of bidder pairs with collusion red flags
- [ ] Description: This table lists all instances for when a co-bidding pair for one of the 8 collusion red flags occurs.

Filters:

- [ ] Bidder

Columns:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-0af4868d-7fff-f393-fbb1-209f4ef37172"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
Bidder name 1 | The name of the bidder. The OCDS field is parties/name. The field award/supplier/name may also be used. | Users can click on the bidder name to go to the Individual Bidders Dashboard. Users can filter for a specific bidder.
Bidder name 2 | The name of the bidder. The OCDS field is parties/name. The field award/supplier/name may also be used. | Users can click on the bidder name to go to the Individual Bidders Dashboard. Users can filter for a specific bidder.
Number of contracting processes they participated in | Calculated metric on the number of co- occurrences. |  
Red flag | Include a column for each collusion red flag and count the number of times the flag occurs for that pair (both bidders flagged). Flags to include: R022, R023, R024, R028, R025, R034 |  

</div></b>
</body>
</html>

**Comment by vgeryarbc** [comment]
Please check current version. 
Many bidders may have the same flag for one contract process and preferably we have to show them all (not only 'pairs').


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/985288b6-6b16-4c0f-9a91-c70e134293cc)

**Comment by Camilamila** [comment]
The idea of this table is to show co-bidding pairs, to be able to identify how many times does a pair of bidders co-bids and in how many of those procedures flags were raised.  

Currently, this is showing not pairs, but rather for Bidder A, in contracting process X, which are the bidders and if they were flagged.    

Can we adjust the table? We can keep for each pair the column with the lists of ocids.  Also can we add a filter to filter by bidder.

**Comment by vgeryarbc** [comment]
Hi @jpmckinney !
I did not see R028 flag in ecuador_sercop_bulk_result.  R028 helps to design and test this table.

**Comment by vgeryarbc** [comment]
@jpmckinney @Camilamila 
Please check new version.
![image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/50f44970-25fa-41e6-b036-003cd974100c)

**Comment by Camilamila** [comment]
Thanks Vadim!  This is clearer!  The only thing missing is to be able to filter by bidder, is that possible to include?

**Comment by vgeryarbc** [comment]
We have one on tables top header.|


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/35660627-7278-4b45-a09b-e7d0a6fbf85a)

**Comment by Camilamila** [comment]
Thanks Vadim!  Looks good!
