### ISSUE TITLE
Add chart: Proportion of contracting processes involving bidder  that have red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#64]
Chart details:

- [ ] Type: 2-Slice Pie Chart
- [ ] Title: Proportion of contracting processes involving bidder  that have red flags
- [ ] Slice A →  With red flags
- [ ] Slice B → Without red flags

Additional details:
- This counts the red flags where the bidder is flagged found in contracting process.
- Data labels with percentage and value should show upon hover.

**Comment by sabahfromlondon** [comment]
@Camilamila I think we're going to need to make the labels for the pie chart slices shorter.

With the title we have, I think we could just have:
- With red flags
- With no red flags

**Comment by Camilamila** [comment]
Agree.  Updated
