### ISSUE TITLE
Add chart: Most common bidder red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#65]
Chart details:

- [ ] Type: Horizontal bar chart
- [ ] Title: Most common bidder red flags
- [ ] Description: Identify which red flags are raised for the bidder.
- [ ] X-axis → Number of times the red flag is detected
- [ ] Y-axis → Red flag name

**Comment by Camilamila** [comment]
Can we add in the tooltip the **Red flag information** such as the graph in the home page

<img width="752" alt="Screen Shot 2024-06-18 at 14 09 35" src="https://github.com/open-contracting/bi.open-contracting.org/assets/24500400/f7ef3881-6867-4555-84f3-6c1491e0dd48">

**Comment by vgeryarbc** [comment]
Hyperlinks are not supported in tooltips.
We have added a link to Methodology page where red flags explained. Please check if it is OK.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/a94d4cbf-ce6c-4e99-84a2-10ef0b6e597e)
