### ISSUE TITLE
Add table: List of contracting processes the bidder has participated in

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#66]
Table details:

- [ ] Title: List of contracting processes the bidder has participated in
- [ ] Description: A list of contracting processes the bidder has participated in and the red flags associated. Note: A bidder can participate in a flagged contracting processes and not be flagged.

Filters:

- [ ] Buyer name
- [ ] Date range
- [ ] Procurement method
- [ ] Ocid

Columns:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-55df71d2-7fff-bea5-35d6-dc9a81a6044f"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
OCID | The OCDS field ocid. The globally unique identifier for this Open Contracting Process | Each field should link to the specific contracting process, viewable in the Individual Contracting Process dashboard.
Buyer | The name of the entity procuring the goods/services. The OCDS field buyerName. Alternatively use tenderProcuringEntity. | Users can click on the buyer name to go to the Individual Buyers Dashboard. Users can filter for a specific buyer
Tender title | The title of the tender as per the OCDS field tender/title. |  
Date | The timestamp for the contracting process using the OCDS field tender/period/startDate. | Users can filter the contracting processes by selecting a date range.
Procurement method | The method used to procure the goods/services from the closed method codelist. Methods are: ‘open’, ‘selective’, ‘limited’, ‘direct’. | Users can filter by method using a dropdown with the four options. Users can filter by procurement method
Tender value | The value of the tenderand the currency. OCDS fields tender/valueAmount and tender/valueCurrency. | Users can sort by value amount e.g. highest to lowest.
Status | The current status of the tender, from the closed tenderStatus codelist, using the OCDS field tender/status. | Users can filter by status
Number of unique bidders | The number of parties who submit a bid as per the OCDS field tenderNumberOfTenderers. |  
Role | The role of the party that was either a supplier or bidder from the party role codelist. The OCDS field is parties/roles. |  
Number of red flags | The total number of red flags for the bidder in the contracting process. | Users can sort by value e.g. highest to lowest.
Red flag names | The name of the red flag indicator. | Users can filter by red flag name.If there are multiple red flags, have on one row and separate using a semi colon.

</div></b>
</body>
</html>

**Comment by vgeryarbc** [comment]
1. Would you like to add ContractValue after TenderValue (I see only 25k of 160k contracting processes in 2023 have TenderValue)
2. BidderList column was used in DR to show all bidders participated in the ocid. Would you like to display one?

**Comment by Camilamila** [comment]
1. Yes lets use contract value, since I believe the procedures without a tender value are purchase orders from frameworks.  
2. Yes lets add that.
3. Also instead of procurement method, lets use tender/procurementMethodDetails, to list the local procurement methods.

**Comment by jpmckinney** [comment]
> lets use tender/procurementMethodDetails

@vgeryarbc If you use tender/procurementMethodDetails, you'll have to split on `-` and use only the first part, because Ecuador puts the name of the framework agreement after the `-`.

**Comment by vgeryarbc** [comment]
OK. I'll try to split and show first part only for procurementMethodDetails

**Comment by Camilamila** [comment]
Instead of `tender/title` can we use the field `tender/description`?

**Comment by vgeryarbc** [comment]
Title replaced with Description.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/4f7fcbb7-158e-408e-b4a7-9cc4eeea25e3)

**Comment by Camilamila** [comment]
Change ocid filter to `tender/id`.  If possible, can we remove the characters after the last '-'.  For example:

If the `tender/id` is:  `001-LICS-HGFO-2023-54538`,  the value shoulde be `001-LICS-HGFO-2023`

In Spanish the translation should be:  Código del proceso

**Comment by vgeryarbc** [comment]
Changed


![Image](https://github.com/user-attachments/assets/1d18ccc5-33ce-4712-8ed0-ad7669228d05)
