### ISSUE TITLE
Add tile: Buyers with contracting processes with ‘supplier’ red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#70]
Tile details:
- [ ] < Number > and < Percentage > Buyers with contracting processes with ‘supplier’ red flags

**Comment by Camilamila** [comment]
Remove this tile.

**Comment by Camilamila** [comment]
These are competition red flags, they are in the competition red flags dashboard.

**Comment by vgeryarbc** [comment]
Do I have to do something ?

**Comment by Camilamila** [comment]
the action is to remove this tile.

**Comment by vgeryarbc** [comment]
Removed.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/accd351a-79f4-4bb0-bab9-a59891dc0d18)
