### ISSUE TITLE
Add tile: Buyers with contracting processes with ‘prices’ red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#71]
Tile details:
- [ ] < Number > and < Percentage > Buyers with contracting processes with ‘prices’ red flags

**Comment by vgeryarbc** [comment]
No 'Prices' category found in https://docs.google.com/spreadsheets/d/11qQO6l4wgPQuH1aExST21XlyRG1uXOJiAldzz4r7NWI/edit#gid=1498640771
