### ISSUE TITLE
Add chart: Proportion of flagged contracting processes by buyer over time

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#73]
Chart details:

- [ ] Type: Multiple Line Chart
- [ ] Title: Proportion of flagged contracting processes by buyer over time
- [ ] Description: Compare the different buyers' performance over time and highlight potential issues related to seasonality e.g. time pressures on staff.
- [ ] X-axis → Month and year
- [ ] Y-axis → Proportion of flagged contracting processes

Additional details:
- Allow adding of up to five additional buyers for users to compare.

**Comment by Camilamila** [comment]
As it is the chart is not legible.  Could we show just one buyer by default, and then the user could select from a dropdown which buyers to show?

**Comment by vgeryarbc** [comment]
We can select one or more Buyers by default for whole Buyers page.
If we select one Buyer just for  'Proportion of flagged contracting processes by buyer over time' chart we disable crosfiltering between one and other visuals on page and that chart become non responding. 
At present all Buyers are selecetd and if user select some Buyers on filter blow the chart responses to that selection and displays data for selected buyers.
