### ISSUE TITLE
Add table: List of buyers that have contracting processes with red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#74]
Table details:

- [ ] Title: List of buyers that have contracting processes with red flags
- [ ] Description: This table lists buyers that have contracting processes with red flags that they are responsible for. Use this table to help identify which buyers have more risk.

Filters:

- [ ] Buyer name

Columns:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-799f747f-7fff-e66a-b527-ecd610fa0ab7"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
Buyer | The name of the buyer using the OCDS field buyerName. | Users can click on the buyer name to go to the Individual Buyers Dashboard. Users can filter for a specific buyer
Number of contracting processes for buyer | The total number of contracting processes that the buyer is party to. It helps to put the count of red flags columns into context. |  
Proportion of flagged contracting processes | Proportion of contracting processes that are flagged and associated with the buyer. |  
Total number of red flags | This is the total of all of the red flags in contracting processes that are associated with the buyer. | Users can sort by value e.g. highest to lowest.Include note to state that buyers that are involved in more contracting processes is likely to have more red flags
Count of competition red flags | This is the total number of risk to supplier red flags that are associated with the buyer’s contacting processes. |  
Count of collusion detection red flags | This is the total number of collusion detection red flags that are associated with the buyer’s contacting processes. | Include tooltip stating: this type of red flag does not necessarily mean that there is corruption risk with the buyer, but that there might be a problem with the suppliers and bidderswho are bidding.
Count of risk to supplier red flags | This is the total number of risks to supplier red flags that are associated with the buyer’s contacting processes. |  
Count of price red flags | This is the total number of price red flags that are associated with the buyer’s contacting processes. |  

</div></b>
</body>
</html>

**Comment by Camilamila** [comment]
For Ecuador we dont have "Risk to supplier red flags" so lets remove this column from the table.

**Comment by jpmckinney** [comment]
Don't we have R003 (implemented) and R055 (not yet implemented)? https://docs.google.com/spreadsheets/d/11qQO6l4wgPQuH1aExST21XlyRG1uXOJiAldzz4r7NWI/edit#gid=808936397

**Comment by jpmckinney** [comment]
Per #70 these are competition flags.

**Comment by vgeryarbc** [comment]
Column removed.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/a9660802-3f02-47e3-81fd-67bd35290cbe)
