### ISSUE TITLE
Add chart: Proportion of contracting processes for buyer with red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#80]
Chart details:

- [ ] Type: 2-Slice Pie Chart
- [ ] Title: Proportion of contracting processes for buyer with red flags
- [ ] Slice A → Proportion contracting processes for buyer that have red flags
- [ ] Slice B → Proportion contracting processes for buyer that have no red flags

**Comment by Camilamila** [comment]
For values lower than 1000, can we add the actual number (e.g 750), since currently is showing 0.

**Comment by vgeryarbc** [comment]
Fixed to show whole value.
