### ISSUE TITLE
Add chart: Item categories with a higher proportion of contracting processes with red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#83]
Chart details:

- [ ] Type: Horizontal bar chart
- [ ] Title: Item categories with a higher proportion of contracting processes with red flags
- [ ] Identify if there is a higher risk in specific item categories for the particular buyer.
- [ ] X-axis → Proportion of contracting processes in item category with red flags
- [ ] Y-axis → Item category name

Additional details:
- Only the top 10 bars are to be displayed. ‘See all’ button to view the data in a table.  
- Add in tooltip the number of contracting processes for the specific item category.
- **Note: We need to check if there are outliers, e.g  item categories with very few procedures and a high average, to evaluate if we should filter only for top item categories**

**Comment by Camilamila** [comment]
Review title, it should be: "Item categories with a higher proportion of contracting processes with red flags". Currently it says  ...with collusion risk.

**Comment by vgeryarbc** [comment]
Fixed

**Comment by jpmckinney** [comment]
Need to fix highest -> higher

**Comment by vgeryarbc** [comment]
@jpmckinney @Camilamila  Is it OK ?
![image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/7e91ed31-080f-4175-9c5f-4938e2d2bc80)
![image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/d5bad8cf-99ee-4687-880a-6cb3217fc35e)

**Comment by jpmckinney** [comment]
Looks good!
