### ISSUE TITLE
Add table: List of contracting processes for buyer

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#84]
Table details:

- [ ] Title: List of contracting processes for buyer
- [ ] Description: A full list of the buyers' contracting processes and the red flags associated with it. Use this to identify which buyers have more risk.

Filters:
- [ ] Ocid
- [ ] Date range
- [ ] Procurement method
- [ ] Supplier name
- [ ] Status

Columns:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-a97432bf-7fff-4a5e-d101-0ffd7f1a00e0"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
OCID | The OCDS field ocid. The globally unique identifier for this Open Contracting Process. |  
Tender title | The title for the contracting process as per the OCDS field tender/title. | Users can click the tender title and go to the Individual Contracting Processes Dashboard.
Date | The OCDS field tender/startDate. | Users can filter the contracting processes by selecting a date range.
Procurement method | The method used to procure the goods/services. The OCDS field is tender/procurementMethodDetails. | Users can sort by procurement method
Tender value | The value of the contract and the currency. OCDS fields tender/valueAmount and tender/valueCurrency. | Users can sort by value amount e.g. highest to lowest.
Supplier name | The name of the entity supplying the goods/services. The OCDS field supplier/name. | Users can click on the supplier name to go to the Individual Suppliers Dashboard. Users can filter for a specific supplier Can be multiple suppliers. Have all suppliers in one row, semi colon separated
Count of red flags | The total number of red flags for the contracting process | Users can sort by value e.g. highest to lowest.
Red flag name | The name of the red flags indicators, | All red flag names in one row, separated by a semi-colon
Status | The current status of the tender, from the tender/status codelist, using the OCDS field tender/status. | Users can filter by status using a dropdown with the different options.

</div></b>
</body>
</html>

**Comment by sabahfromlondon** [comment]
@Camilamila are you sure you want to use te column heading "Procurement method" for this table, since we are using the field `tender/procurementMethodDetails`?

**Comment by Camilamila** [comment]
Yes we can leave "procurement method" for the heading.

**Comment by sabahfromlondon** [comment]
Ok thanks, I've updated the filter as well

**Comment by Camilamila** [comment]
The procurement method column should use the field `tender/procurementMethodDetails`

**Comment by vgeryarbc** [comment]
Done

**Comment by jpmckinney** [comment]
<img width="152" alt="Screenshot 2024-05-30 at 1 35 39 AM" src="https://github.com/open-contracting/bi.open-contracting.org/assets/26463/519a5313-6653-4c1d-bc25-969dc4b8b974">

**Comment by Camilamila** [comment]
Instead of `tender/title` can we use the field `tender/description`?

**Comment by vgeryarbc** [comment]
Changed to tender/description.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/688c4b6a-5ab8-4df7-80c9-dd7e07e7beb0)

**Comment by Camilamila** [comment]
Change ocid filter to `tender/id`.  If possible, can we remove the characters after the last '-'.  For example:

If the `tender/id` is:  `001-LICS-HGFO-2023-54538`,  the value shoulde be `001-LICS-HGFO-2023`

In Spanish the translation should be:  Código del proceso

**Comment by vgeryarbc** [comment]
Changed


![Image](https://github.com/user-attachments/assets/45cac5f4-ccad-466a-a840-a620dcc627d1)
