### ISSUE TITLE
Add tile: Contracting processes with 3+ red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#86]
Tile details:
- [ ] < Number > and < Percentage > Contracting processes with 3+ red flags

**Comment by jpmckinney** [comment]
Confirmed. Closing.

<img width="460" alt="Screenshot 2024-05-16 at 9 14 16 PM" src="https://github.com/open-contracting/bi.open-contracting.org/assets/26463/e1cc8e3c-a4ca-49b4-b383-4b3c815ab076">
