### ISSUE TITLE
Add tile: Mean number of red flags per contracting process

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#87]
Tile details:
- [ ] < Number > Mean number of red flags per contracting process

**Comment by jpmckinney** [comment]
Confirmed. Closing.

<img width="466" alt="Screenshot 2024-05-16 at 9 13 55 PM" src="https://github.com/open-contracting/bi.open-contracting.org/assets/26463/267b9ca1-d5d5-4c65-a65f-9a68c99ee4ab">
