### ISSUE TITLE
Add tile: Contracting processes with ‘supplier’ red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#90]
Tile details:
- [ ] < Number > and < Percentage > Contracting processes with ‘supplier’ red flags

**Comment by Camilamila** [comment]
Remove this tile

**Comment by jpmckinney** [comment]
My same comment as #70

**Comment by vgeryarbc** [comment]
Removed. 


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/19a5e395-c65a-48e5-a962-3dc4cef1badc)

@Camilamila  @jpmckinney would you like to remove "Number of 'risk to supplier' red flag column in the table below ?


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/ef043766-03ae-4d7c-8203-7397e273e87a)

**Comment by Camilamila** [comment]
Yes! I see its already removed, so closing the issue
