### ISSUE TITLE
Add table: Contracting process red flags

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#92]
Table details:

- [ ] Title: Contracting process red flags
- [ ] Description: A list of all the red flags associated with contracting processes. Filter by the Item Category, Buyer Name, Supplier Name, Procurement Method and the Status of the contracting process.

Filters:
- [ ] Ocid
- [ ] Buyer name
- [ ] Procurement method details
- [ ] Date range
- [ ] Item category
- [ ] Supplier name
- [ ] Status

Columns:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-bd147f92-7fff-b3e9-b385-aff34b50ae5f"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
OCID | The OCDS field ocid. The globally unique identifier for this Open Contracting Process |  
Tender title | The title of the contract as per the OCDS field tender/title. |  
Buyer | The name of the entity procuring the goods/services. The OCDS field buyerName. Alternatively use tender/procuringEntity. | Users can click on the buyer name to go to the Individual Buyers Dashboard. Users can filter for a specific buyer
Procurement method | The method used to procure the goods/services from the method codelist. The OCDS field is tender/procurementMethodDetails. | Users can filter by procurement method
Tender value | The value of the contract and the currency. OCDS fields tender/valueAmount and tender/valueCurrency. | Users can sort by value amount e.g. highest to lowest.
Item category | The classification of the item using the OCDS field tender/items/classification/ description and high level UNSPSC codes. | Users can filter for a specific categoryCan be multiple item categories. Have all item categories in one row, semi colon separated
Date | The timestamp for the contracting process using the OCDS field tender/period/startDate. | Users can filter the contracting processes by selecting a date range for the tender/startDate.
Number of unique bidders | The number of parties who submit a bid as per the OCDS field tender/numberOfTenderers. | Users can sort by value e.g. highest to lowest.
Number of all red flags | This is the total of all of the red flags in contracting processes that are associated with the buyer. | Users can sort by value e.g. highest to lowest.Include note stating: Buyers involved in more contracting processes are likely to have more red flags
Number of competition red flags | This is the total of all of the competition red flags associated with the contracting process. | Users can sort by value e.g. highest to lowest.
Number of collusion detection red flags | This is the total of all of the collusion detection red flags that are associated with the contracting process. | Users can sort by value e.g. highest to lowest.
Number of supplier red flags | This is the total of all of the risk to supplier red flags that are associated with the contracting process. | Users can sort by value e.g. highest to lowest.
Number of prices red flags | This is the total of all of the prices red flags that are associated with the contracting process. | Users can sort by value e.g. highest to lowest.
Supplier name | The name of the supplier,. The OCDS field is parties/name. The field award/supplier/name may also be used. | Can be multiple suppliers. Have all suppliers in one row, semi colon separated
Status | The current status of the tender, from the closed tenderStatus codelist, using the OCDS field tender/status. | Users can filter by status

</div></b>
</body>
</html>

**Comment by Camilamila** [comment]
Instead of `tender/title` can we use the field `tender/description`?

**Comment by vgeryarbc** [comment]
Changed to tender/description.


![Image](https://github.com/open-contracting/bi.open-contracting.org/assets/142454157/d4e102c1-19d8-4851-86b0-7da188b98e27)

**Comment by Camilamila** [comment]
Change ocid filter to `tender/id`.  If possible, can we remove the characters after the last '-'.  For example:

If the `tender/id` is:  `001-LICS-HGFO-2023-54538`,  the value shoulde be `001-LICS-HGFO-2023`

In Spanish the translation should be:  Código del proceso

**Comment by vgeryarbc** [comment]
Changed


![Image](https://github.com/user-attachments/assets/9300c409-cc08-40c2-9a0e-77adfb654010)
