### ISSUE TITLE
Add information about the contracting process

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#93]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-af5d957e-7fff-5321-f83c-a8a5502e5de1"><div dir="ltr" style="margin-left:0pt;" align="left">

Data | Field Description | Requirements
-- | -- | --
Supplier(s) name | Name of the awarded supplier(s). | Can be multiple suppliers for a single contracting process. Include all.
Buyer name | The name of the buyer using the OCDS field buyerName. Alternatively, use tender/procuringEntity. |  
OCID | The OCDS field ocid. The globally unique identifier for this Open Contracting Process. |  
Status | The current status of the tender, from the closed tenderStatus codelist, using the OCDS field status. |  

</div></b>
</body>
</html>

**Comment by Camilamila** [comment]
Add Procurement Method details in table

**Comment by Camilamila** [comment]
Change ocid  to `tender/id`.  If possible, can we remove the characters after the last '-'.  For example:

If the `tender/id` is:  `001-LICS-HGFO-2023-54538`,  the value shoulde be `001-LICS-HGFO-2023`

In Spanish the translation should be:  Código del proceso

**Comment by vgeryarbc** [comment]
I think it is dangerous to cut ocid last part here. We have to select ocid to choose individual contracting process exactly. 
Now I have deleted the prefix only.


![Image](https://github.com/user-attachments/assets/feb5facb-8710-449b-9e3c-f842470dbe90)
