### ISSUE TITLE
Add table: 

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/bi.open-contracting.org#98]
Table details:

- [ ] Title: List of bidders and bid amounts
- [ ] Description: A full list of bidders for the contracting processes, their bid values and if they were disqualified from the contracting process or not. Use this table to identify risks to the supplier from unfair disqualification

Columns:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-6413647d-7fff-d5a3-a907-b10f75fea552"><div dir="ltr" style="margin-left:0pt;" align="left">

Column Heading | Field Description | Requirements
-- | -- | --
Bidder name | This is the name of a bidder for the contracting process. | Some bidders will become suppliers if they win, these also need to be included in this table.
Bid amount | This is the value of the bid made by each bidder for the contracting process. OCDS fields tender/valueAmount and tender/valueCurrency. | Allow users to sort by the bid amount, ascending and descending.
Bidder status | This is a boolean field. Bidders are either “Qualified” or “Disqualified”. |  
Bid date | The date of the bid |  
Red flag(s) | An indicator if the bidder was flagged for this bid in the procedure. |  
Bidder red flag(s) | Name(s) of the flag(s) detected.  A bidder can be flagged for one or more flags in the procedure | Flags to include:  R022, R023, R024, R028, R034, R035, R036, R058

</div></b>
</body>
</html>

**Comment by vgeryarbc** [comment]
'Bid ID' needs to be added to avoid summarization bid amount from the same bidder. OK?

**Comment by jpmckinney** [comment]
Yes. That's what we did last time we had unwanted summarization, right?

**Comment by vgeryarbc** [comment]
Yes!
